export default {
  link__text: {
    fontSize: "11px",
    textTransform: "uppercase",
    fontWeight: "medium",
    color: "#454545",
  },
  section__title: {
    fontSize: "14px",
    fontWeight: "medium",
    color: "#454545",
    textTransform: "uppercase",
  },
  btn__filled: {
    fontSize: { base: "14px", sm: "15px" },
    h: { base: "36px", sm: "40px" },
    color: "#fff",
    bg: "#111",
    px: "24px",
    fontWeight: "normal",
    borderRadius: "unset",
    _active: { background: "#111" },
    _hover: { background: "#111" },
    _focus: { boxShadow: "unset" },
  },
  btn__outlined: {
    fontSize: { base: "14px", sm: "15px" },
    h: { base: "36px", sm: "40px" },
    color: "#111",
    bg: "transparent",
    fontWeight: "normal",
    borderRadius: "unset",
    border: "1px",
    px: "24px",
    borderColor: "#111",
    _active: { background: "unset" },
    _hover: { background: "unset" },
    _focus: { boxShadow: "unset" },
  },
  btn__neutral: {
    fontSize: { base: "14px", sm: "15px" },
    h: { base: "36px", sm: "40px" },
    color: "#111",
    bg: "transparent",
    px: "24px",
    fontWeight: "normal",
    borderRadius: "unset",
    _active: { background: "blackAlpha.100" },
    _hover: { background: "blackAlpha.100" },
    _focus: { boxShadow: "unset" },
  },
  site__logo: {
    fontSize: "20px",
    textAlign: "center",
    cursor: "pointer",
    color: "#111",
  },
  input: {
    borderRadius: "unset",
    _focus: {
      borderColor: "#454545",
      boxShadow: "0 0 0 .2px #454545",
    },
    color: "#111",
  },
  input__label: {
    fontSize: "14px",
    color: "#111",
  },
};
